# IoT Edge CI Build Definition
# Build your IoT Edge Modules in Azure DevOps
# https://aka.ms/yaml

pool:
  name: "ARM"

steps:
  - task: CopyFiles@2
    displayName: "Copy unaltered source to: $(Build.ArtifactStagingDirectory)"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)"
      Contents: "/**/*.*"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: "Replace tokens in deployment.template.json"
    inputs:
      rootDirectory: MeatGeek-IoT-Edge
      targetFiles: deployment.template.json

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: "Replace tokens in modules/**/module.json"
    inputs:
      rootDirectory: MeatGeek-IoT-Edge
      targetFiles: "modules/**/module.json"

  - task: AzureIoTEdge@2
    displayName: "Azure IoT Edge - Build module images"
    inputs:
      deploymentid: "azuredevops-deployment"
      templateFilePath: MeatGeek-IoT-Edge/deployment.template.json
      defaultPlatform: arm32v7

  - task: AzureIoTEdge@2
    displayName: "Azure IoT Edge - Push module images"
    inputs:
      action: "Push module images"
      deploymentid: "vsts-deployment"
      azureSubscriptionEndpoint: "Visual Studio Enterprise (2394ff5d-4d73-4134-a00f-2385754aeeb5)"
      azureContainerRegistry: '{"loginServer":"meatgeek.azurecr.io", "id" : "/subscriptions/2394ff5d-4d73-4134-a00f-2385754aeeb5/resourceGroups/MeatGeek-Shared/providers/Microsoft.ContainerRegistry/registries/meatgeek"}'
      templateFilePath: "$(System.DefaultWorkingDirectory)/$(Release.PrimaryArtifactSourceAlias)/drop/MeatGeek-IoT-Edge/deployment.template.json"
      defaultPlatform: arm32v7

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
